#!/usr/bin/env bash

OPTIND=1
rcfile="${XDG_CONFIG_HOME}/humblepie.rc"
[[ -f "${rcfile}" ]] && . "${rcfile}"

## options
# -d [path]: directory where game should exist
# -g [game]: which game to perform work on
# -h: print usage
# -k [key]: set HiB key
# -t [path]: directory where torrent files should exist
# -v: verbosity
# need something for specifying system to determine which download to grab
# also need to ask which version of the game to use; 32bit, 64bit, deb, tarball

while getopts "d:g:hk:t:v?" opt; do
  case "$opt" in
    d) ## set the download/game dir
      hibdir="${OPTARG}"
      gamedir
      ;;
    g) ## do the game stuff; probably _checkgame && _dlgame
      hibgame="${OPTARG}"
      ;;
    h|\?) ## print usage
      ;;
    k) ## set the key to use
      hibkey="hib_${OPTARG}"
      ;;
    t) ## set the .torrent dir
      hibtorr="${OPTARG}"
      torrdir
      ;;
    v) ## turn on verbosity
      ;;
  esac
done

gamedir() {
  [[ -w "${hibdir}" ]] || {
    echo "Error: ${hibdir} does not exist or you do not have writable permissions!"
    exit 1
  }
}

torrdir() {
  [[ -w "${hibtorr}" ]] || {
    echo "Error: ${hibtorr} does not exist or you do not have writable permissions!"
    exit 1
  }
}

_dlgame() {
  local uri
  uri="$(curl -s http://www.humblebundle.com/downloads?key="${hibkey}" \
    | grep "${hibgame}")"
  echo "  1. Torrent with aria2c"
  echo "  2. HTTP with curl"

  echo -n "Choose download method: "
  read -a method
  case "${method}" in
    1)
      if [[ -x "$(type -p aria2c)" ]]; then
        uri="${uri##*data-bt\=\'}"
        uri="${uri%%\'*}" 
        echo "To resume this download later run:"
        echo "\`aria2c ${pkgname}.torrent\`"
        [[ ! -f "${pkgname}.torrent" ]] &&
          curl -o "${pkgname}.torrent" "${uri}"
        aria2c "${pkgname}.torrent" --seed-time=0
        mv "${pkgname}.torrent" "${hibtorr}"
      else
        echo "aria2c executable not found! Please install aria2."
      fi
    } ;;
  2)
    uri="${uri##*data-web\=\'}"
    uri="${uri%%\'*}" 
    [[ -f "${hibgame}.part" ]] &&
      curl -o "${hibgame}.part" "${uri}"
    mv "${hibgame}.part" "${hibgame}" ;;
  *) echo "Please choose option 1 or 2." ;;
  esac
}

# [[ -f "${hibdir}/${hibgame}" ]] && {
#   ln -sf "${hibdir}/${hibgame}" .
# }

# _genkeyarray() {

# _checkkey
# }

# _checkkey() {
#   for keyvar in "${hibkeyarray[@]}"; do
#   hibkey="keyvar"
#   [[ -n "${hibkey}" ]] && break
#   done
#   _checkgame
# }

# _checkgame() {
  # [[ -f "${hibgame}" ]] || {
  #   local prompt="Absolute path (omit trailing slashes): "
  #   [[ -d "${hibdir}" ]] && {
  #   echo "Specify the path to the directory containing ${hibgame}"
  #   echo -n "${prompt}"
  #   while read -er _dir; do
  #     while [[ -f "${_dir}/${hibgame}" ]]; do
  #       [[ $(md5sum "${_dir}/${hibgame}") == ${md5sum[0]} ]] {
  #         ln -sf "${_dir}/${hibgame}" .
  #         export hibdir="${_dir}"
  #     }
  #     done
  #   done
  #   }

  #   echo "Y to specify path to existing download, blank to specify your humble indie bundle key."
  #   echo "Alternatively, place the download into ${hibdir} and retry."
  #   read -r cont

  #   case "${cont}" in
  #     [yY]) _dlgame
  #       ;;
  #     *) echo "Specify your humble indie bundle key."
  #       echo -n "Humble Indie Bundle key: "
  #       read -r _hib
  #       [[ -n "${_hib}" ]] && hibkey="_hib"
  #       ;;
  #   esac
  # }
# }

