#!/usr/bin/env bash
###############################################################################
### thanks to:
### JavaAtom <faustian.merula@gmail.com>: filename generation for Introversion
###
###
###############################################################################
## covered bundles:
##  4, 5, frozensynapse, introversion(maybe?)
OPTIND=1
rcfile="${XDG_CONFIG_HOME}/humblepie.rc"
[[ -f "${rcfile}" ]] && . "${rcfile}"

declare -a bundlekeys

bundlekeys=('hib1key' 
            'hib2key'
            'hib3key'
            'hib4key'
            'hib5key'
            'hibandroid1key'
            'hibandroid2key'
            'hibbotaniculakey'
            'hibfrozenbytekey'
            'hibfrozensynapsekey'
            'hibintroversionkey'
            'hibmojangkey'
            'hibvoxatronkey'
            )

declare -Ar hib1 hib2 hib3 hib4 hib5
declare -Ar hibandroid1 hibandroid2
declare -Ar hibbotanicula hibfrozenbyte
declare -Ar hibfrozensynapse hibintroversion
declare -Ar hibmojang hibvoxatron

hib1=( 
      ["aquaria"]="aquaria"
      ["gish"]="gish"
      ["lugaruhd"]="lugaruhd"
      ["lugaru"]="lugaruhd"
      ["lhd"]="lugaruhd"
      ["penumbra"]="penumbraoverture"
      ["po"]="penumbraoverture"
      ["samorost2"]="samorost2"
      ["s2"]="samorost2"
      ["worldofgoo"]="worldofgoo" 
      ["wog"]="worldofgoo"
      )
hib2=( 
      ["braid"]="braid"
      ["cortexcommand"]="cortexcommand" 
      ["cc"]="cortexcommand"
      ["osmos"]="osmos"
      ["machinarium"]="machinarium"
      ["revengeofthetitans"]="revengeofthetitans" 
      ["rott"]="revengeofthetitans"
      )
hib3=( 
      ["andyetitmoves"]="andyetitmoves" 
      ["ayim"]="andyetitmoves"
      ["atomzombiesmasher"]="atomzombiesmasher" 
      ["azs"]="atomzombiesmasher"
      ["cogs"]="cogs"
      ["crayonphysicsdeluxe"]="crayonphysicsdeluxe"
      ["crayonphysics"]="crayonphysicsdeluxe"
      ["cpd"]="crayonphysicsdeluxe"
      ["hammerfight"]="hammerfight" 
      ["hf"]="hammerfight"
      ["steelstormretribution"]="steelstormretribution"
      ["steelstorm"]="steelstormretribution" 
      ["ssr"]="steelstormretribution"
      ["ss"]="steelstormretribution"
      ["vvvvvv"]="VVVVVV" ["v"]="VVVVVV"
      )
hib4=( 
      ["bittriprunner"]="bit.trip.runner" 
      ["btr"]="bit.trip.runner"
      ["cavestoryplus"]="cavestoryplus" 
      ["cavestory"]="cavestoryplus"
      ["csp"]="cavestoryplus"
      ["jamestown"]="jtownlinux" 
      ["jtown"]="jtownlinux" 
      ["jt"]="jtownlinux"
      ["nightskyhd"]="nightskyhd" 
      ["nightsky"]="nightskyhd"
      ["nshd"]="nightskyhd" 
      ["ns"]="nightskyhd"
      ["shank"]="shank"
      ["supermeatboy"]="supermeatboy" 
      ["smb"]="supermeatboy"
      )
hib5=( 
      ["amnesiatdd"]="amnesiatdd" 
      ["amnesia"]="amnesiatdd" 
      ["bastion"]="bastion"
      ["braid"]="braid"
      ["limbo"]="limbo"
      ["lonesurvivor"]="lonesurvivor" 
      ["survivor"]="lonesurvivor"
      ["ls"]="lonesurvivor"
      ["psychonauts"]="psychonauts" 
      ["pn"]="psychonauts"
      ["supermeatboy"]="supermeatboy" 
      ["smb"]="supermeatboy"
      ["swordandsworcery"]="swordandsworcery" 
      ["s&s"]="swordandsworcery"
      ["sas"]="swordandsworcery"
      )
hibandroid1=( 
            ["anomalywarzoneearth"]="anomalywarzoneearth" 
            ["anomaly"]="anomalywarzoneearth"
            ["edge"]="edge"
            ["osmos"]="osmos"
            ["tokitori"]="tokitori" 
            ["toki"]="tokitori" 
            ["tt"]="tokitori"
            ["worldofgoo"]="worldofgoo" 
            ["wog"]="worldofgoo" 
            )
hibandroid2=( 
            ["avadontheblackfortress"]="avadontheblackfortress"
            ["avadon"]="avadontheblackfortress"
            ["atbf"]="avadontheblackfortress"
            ["canabalt"]="canabalt"
            ["cogs"]="cogs"
            ["snuggletruck"]="snuggletruck" 
            ["st"]="snuggletruck"
            ["swordsandsoldiers"]="swordsandsoldiers"
            ["s&s"]="swordsandsoldiers" 
            ["sas"]="swordsandsoldiers"
            ["zenbound2"]="zenbound2" 
            ["zenbound"]="zenbound2"
            ["zb2"]="zenbound2" 
            ["zb"]="zenbound2" 
            )
hibbotanicula=( 
              ["botanicula"]="botanicula"
              ["machinarium"]="machinarium"
              ["samorost2"]="samorost2" 
              ["samorost"]="samorost2"
              ["s2"]="samorost2" 
              )
hibfrozenbyte=( 
              ["jackclawbeta"]="claw" 
              ["jackclaw"]="claw"
              ["jcb"]="claw" 
              ["jc"]="claw"
              ["shadowgrounds"]="shadowgrounds" 
              ["sg"]="shadowgrounds"
              ["shadowgroundssurvivor"]="survivor" 
              ["sgs"]="surivor"
              ["splot"]="splot"
              ["trine"]="Trine" 
              )
hibfrozensynapse=( 
                  ["frozensynapse"]="frozensynapse" 
                  ["fs"]="frozensynapse"
                  ["spacechem"]="spacechem" 
                  ["sc"]="spacechem"
                  ["trauma"]="tramua"
                  )
hibintroversion=( 
                ["aquaria"]="aquaria"
                ["crayonphysicsdeluxe"]="crayonphysicsdeluxe"
                ["crayonphysics"]="crayonphysicsdeluxe"
                ["cpd"]="crayonphysicsdeluxe"
                ["darwinia"]="darwinia" 
                ["dw"]="darwinia"
                ["defcon"]="defcon"
                ["dugeonsofdredmoor"]="dugeonsofdredmoor"
                ["dod"]="dungeonsofdredmoor"
                ["multiwinia"]="multiwinia" 
                ["mw"]="multiwinia"
                ["uplink"]="uplink" 
                ["ul"]="uplink"
                )
hibmojam=( 
          ["catacombsnatch"]="catacombsnatch" 
          ["cs"]="catacombsnatch"
          ["fistsofresistance"]="fistsofresistance" 
          ["for"]="fistsofresistance"
          ["thebroadsideexpress"]="thebroadsideexpress"
          ["tbse"]="thebroadsideexpress"
          )
hibvoxatron=( 
            ["blocksthatmatter"]="blocksthatmatter" 
            ["btm"]="blocksthatmatter"
            ["chocolatecastle"]="chocolatecastle" 
            ["cc"]="chocolatecastle"
            ["gish"]="gish"
            ["jaspersjourneys"]="jaspersjourneys" 
            ["jj"]="jaspersjourneys"
            ["thebindingofisaac"]="thebindingofisaac"
            ["tboc"]="thebindingofisaac" 
            ["voxatron"]="voxatron" 
            ["vox"]="voxatron"
            ["zenpuzzlegarden"]="zenpuzzlegarden" 
            ["zpg"]="zenpuzzlegarden"
            )

## options
# -a [architecture]: i386, i686, amd64, x86_64, all
# -b [bundle]: which bundle to use
# -d [path]: directory where game should exist
# -g [game]: which game to perform work on
# -h: print usage
# -k [key]: set HiB key
# -t [path]: directory where torrent files should exist
# -v: verbosity
# need something for specifying system to determine which download to grab
# also need to ask which version of the game to use; 32bit, 64bit, deb, tarball

while getopts "vha:d:g:k:t:" opt; do
  case "$opt" in
    a) ## send to a function to set the right arch
      ### there is no convention in the downloads so...
      ### i have to depend on gamename to sanitize it
      hibarch="${OPTARG}"
      ;;
    d) ## set the download/game dir
      hibdir="${OPTARG}"
      gamedir
      ;;
    g) ## do the game stuff; probably _checkgame && _dlgame
      hibgame="${OPTARG}"
      ;;
    h) ## print usage
      ;;
    k) ## set the key to use
      checkkey
      ;;
    t) ## set the .torrent dir
      hibtorr="${OPTARG}"
      torrdir
      ;;
    v) ## turn on verbosity
      ;;
  esac
done

gamedir() {
  [[ -w "${hibdir}" ]] || {
    echo "Error: ${hibdir} does not exist or you do not have writable permissions!"
    exit 1
  }
}

torrdir() {
  [[ -w "${hibtorr}" ]] || {
    echo "Error: ${hibtorr} does not exist or you do not have writable permissions!"
    exit 1
  }
}
checkkey() {
  local k
  k="hib${OPTARG}key"
  for v in "${!bundlekeys[@]}"; do
    if [[ "${v}" == "${!k}" ]]; then
      ## need to verify this loop
      hibkey="${v}"
      checkbundle
    else
      echo "${k} was not found!"
    fi
  done
}

checkbundle() {
  case "${hibkey}" in
    ## set my important values to variables and kick to the downloader
    hib1key) hib1;;
    hib2key) hib2;;
    hib3key) hib3;;
    hib4key) hib4;;
    hib5key) hib5;;
    hibandroid1key) hibandroid1;;
    hibandroid2key) hibandroid2;;
    hibbotaniculakey) hibbotanicula;;
    hibfrozenbytekey) hibfrozenbyte;;
    hibfrozensynapsekey) hibfrozensynapse;;
    hibintroversionkey) hibintroversion;;
    hibmojamkey) hibmojam;;
    hibvoxatronkey) hibvoxatron;;
  esac
}

_dlgame() {
  local uri
  uri="$(curl -s http://www.humblebundle.com/downloads?key="${!hibkey}" \
    | grep "${hibgame}")"
  echo "  1. Torrent with aria2c"
  echo "  2. HTTP with curl"

  echo -n "Choose download method: "
  read -a method
  case "${method}" in
    1)
      if [[ -x "$(type -p aria2c)" ]]; then
        uri="${uri##*data-bt\=\'}"
        uri="${uri%%\'*}" 
        echo "To resume this download later run:"
        echo "\`aria2c ${pkg}.torrent\`"
        [[ ! -f "${pkg}.torrent" ]] &&
          curl -o "${pkg}.torrent" "${uri}"
        aria2c "${pkg}.torrent" --seed-time=0
        mv "${pkg}.torrent" "${hibtorr}"
      else
        echo "aria2c executable not found! Please install aria2."
      fi
    } ;;
  2)
    uri="${uri##*data-web\=\'}"
    uri="${uri%%\'*}" 
    [[ -f "${hibgame}.part" ]] &&
      curl -o "${hibgame}.part" "${uri}"
    mv "${hibgame}.part" "${hibgame}" ;;
  *) echo "Please choose option 1 or 2." ;;
  esac
}

# gamever() {
#   for _key in "${hibgames[@]}"; do
#     case "${_key}" in
#       ## all of these games have shit naming conventions
#       andyetitmoves)
#         ## andyetitmoves-1.2.2-1_x86_64.tar.gz
#         ver="1.2.2-1"
#         break
#         ;;
#       bittriprunner) ## pfft
#         ## bit.trip.runner_amd64.tar.gz
#         break
#         ;;
#       braid) 
#         ## braid_1.0.0-0ubuntu2_amd64.deb
#         ver="1.0.0-0"
#         break
#         ;;
#       cavestoryplus)
#         ## cavestoryplus-linux-1324519044.tar.gz
#         ver="1324519044"
#         platform="linux"
#         break
#         ;;
#       claw)
#         ## clawBeta3.zip
#         ver="Beta3"
#         break
#         ;;
#       cogs) 
#         ## cogs_20110811_all.tar.gz
#         ver="20110811"
#         break
#         ;;
#       crayonphysicsdelux)
#         ## crayon-physics-deluxe_55_i386.tar.gz
#         ver="55"
#         break
#         ;;
#       gratuitousspacebattles)
#         ## gsb1324679796.tar.gz
#         ver="1324679796"
#         break
#         ;;
#       hammerfight)
#         ## hammerfight_1.004_all.tar.gz
#         ver="1.004"
#         break
#         ;;
#       jamestown)
#         ## jtownlinux_1_0_1_1324610248.zip
#         ver="1_0_1_1324610248"
#         break
#         ;;
#       lonesurvivor)
#         ## lonesurvivor-1.11d-amd64.tar.gz
#         ver="1.11d"
#         break
#         ;;
#       nightskyhd)
#         ## nightskyhd-linux-1324519044.tar.gz
#         ver="1324519044"
#         platform="linux"
#         break
#         ;;                   
#       psychonauts)
#         ## psychonuts-linux-test-06032012.tar.bz2
#         ver="06032012"
#         platform="linux"
#         break
#         ;;
#       shadowgrounds)
#         ## shadowgroundsUpdate1.run
#         ver="Update1"
#         break
#         ;;
#       shank)
#         ## shank-linux-120720110-1-bin
#         ver="120720110-1"
#         break
#         ;;
#       supermeatboy)
#         ## supermeatboy-linux-06072012-bin
#         ver="06072012"
#         platform="linux"
#         break
#         ;;
#       survivor)
#         ## survivorUpdate1.run
#         ver="Update1"
#         break
#         ;;
#       VVVVVV)
#         ## VVVVVV_2.01_Linux.tar.gz
#         ver="2.01"
#         platform="Linux"
#         break
#         ;;
#       *) echo "Sorry, ${_key} is not yet supported." ;;
#     esac
#   done
# }
# [[ -f "${hibdir}/${hibgame}" ]] && {
#   ln -sf "${hibdir}/${hibgame}" .
# }

# _genkeyarray() {

# _checkkey
# }

# _checkkey() {
#   for keyvar in "${hibkeyarray[@]}"; do
#   hibkey="keyvar"
#   [[ -n "${hibkey}" ]] && break
#   done
#   _checkgame
# }

# _checkgame() {
  # [[ -f "${hibgame}" ]] || {
  #   local prompt="Absolute path (omit trailing slashes): "
  #   [[ -d "${hibdir}" ]] && {
  #   echo "Specify the path to the directory containing ${hibgame}"
  #   echo -n "${prompt}"
  #   while read -er _dir; do
  #     while [[ -f "${_dir}/${hibgame}" ]]; do
  #       [[ $(md5sum "${_dir}/${hibgame}") == ${md5sum[0]} ]] {
  #         ln -sf "${_dir}/${hibgame}" .
  #         export hibdir="${_dir}"
  #     }
  #     done
  #   done
  #   }

  #   echo "Y to specify path to existing download, blank to specify your humble indie bundle key."
  #   echo "Alternatively, place the download into ${hibdir} and retry."
  #   read -r cont

  #   case "${cont}" in
  #     [yY]) _dlgame
  #       ;;
  #     *) echo "Specify your humble indie bundle key."
  #       echo -n "Humble Indie Bundle key: "
  #       read -r _hib
  #       [[ -n "${_hib}" ]] && hibkey="_hib"
  #       ;;
  #   esac
  # }
# }

