#!/usr/bin/env bash
# vim: ft=sh
# set -x

generate_list() {
  ## send the value of the chosen $hibkey_*; the rest is automagic
  local key="$1"
  local prefix="${USER}-${hib_bundle}-${key}"
  local dump="${prefix}-dump.txt"

  links -html-numbered-links 1 \
    -dump https://www.humblebundle.com/downloads\?key\="${key}" >$dump

  declare -a list
  ## generate the array as a list of game filenames
  while read -r line; do
    list+=("$line")
  done <$dump

  declare -Ag newlist
  for a in "${list[@]}"; do
    ## i want every element that matches *files*/ ...
    b="${a##*files*/}"
    [[ $b == "$a" ]] || {
      ## and then from those, strip ?key=* out of the end
      c="${b%%?key*}"
      ## and finally, everything from &t= onward is the md5sum, weird
      d="${b##*t=}"
      ## dump it into an associative array to get games by name
      newlist+=(["$c"]="$d")
    }
  done
}

dl_game() {
  set -x
  ## now build another array to complete the reference loop
  ## this array is designed to assign $num to game filenames
  ## then present the user with the printf, and when they input 1...
  ## ...i use ${userlist[$num]} to get the game's filename
  local num=1
  declare -ag userlist
  for f in "${!newlist[@]}"; do
    userlist[$num]="$f"
    # printf '%s\t%s\t%s\n' "$num" "$f" "${newlist[$f]}"
    printf '%s\t%s\t%s\n' "$num" "${userlist[$num]}" "${!userlist[$num]}"
    ((num++))
  done
  printf '%s' "Choose game: "
  while read -r game; do
  curl -o "${dir_hib}/${userlist[$game]}" \
    "https://files.humblebundle.com/${userlist[$game]}?key=${!hib_key}&t=${!newlist[$game]}" || break
  done
}
